### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by gjmhmm8** [N-Wither/Omniworld-R#6]
[Uploading crash-2024-02-22_16.33.37-client.txt…]()

**Comment by gjmhmm8** [comment]
[crash-2024-02-22_16.33.37-client.txt](https://github.com/N-Wither/Omniworld-R/files/14371073/crash-2024-02-22_16.33.37-client.txt)

**Comment by N-Wither** [comment]
fixed in 3.5.0
